from hashlib import sha1

from . import project
from .target import Target
from .registry import *
from .ninja_syntax import Writer
from .humanhash import humanize


def ninja_gen(target: Target, manifests: list[Manifest]):
    writer = Writer((project.build_dir() / "ninja.build").open("w"))

    hash = sha1(f"{target.hash.hexdigest()}{manifests.hash.hexdigest()}".encode())

    writer.comment("This file is autogenerated by buildkit")
    writer.comment(f"Build hash: {hash.hexdigest()} ({humanize(hash.hexdigest())})")
    writer.newline()

    writer.variable("builddir", project.build_dir() / humanize(hash.hexdigest()))

    writer.separator("Tools")
